# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterField(
            model_name='product',
            name='average_coast',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Preço médio'),
        ),
    ]
