# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170526_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_coast',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preço médio'),
        ),
    ]
