# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 16:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='created_date',
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Data da compra'),
        ),
    ]
