# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 17:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170526_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 26, 13, 48, 5, 802312), verbose_name='Data da compra'),
        ),
    ]
