# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 02:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170526_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2017, 5, 26, 22, 6, 30, 583574), verbose_name='Data da compra'),
        ),
    ]
