# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 13:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170527_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2017, 5, 27, 13, 16, 9, 329343, tzinfo=utc), verbose_name='Data da compra'),
        ),
    ]
